images/images/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from images import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_pages.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('friend/', include('friend.urls', namespace='friend'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('registrate/', views.RegistrateUserView.as_view(), name='registrate'),
    path('password_change/', views.UserChangePassword.as_view(), name='password_change'),
    path('password_change_done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('search_users/', views.UsersSearch.as_view(), name='search_users'),
    path('update_profile', views.UserUpdateProfile.as_view(), name='update_profile'),
    path('<slug:username>/', views.ShowUserProfile.as_view(), name='profile'),
]

images/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css"  href="{% static 'main_pages/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'main_pages/css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<header>
{% block navigation %}
<nav>
    <div class="d-flex align-items-center">
        <a class="a_logo" href="{% url 'home' %}"><img src="{% static 'main_pages/images/logo2.png'%}" alt="логотип" class="logo"></a>
        <form method="get" onsubmit="return searchUsers();">
            <div class="input-group">
                <input id="q" class="form-control" type="text" placeholder="Поиск..." name="q">
                <button class="btn btn-light" type="submit">Найти</button>
            </div>

        </form>
    </div>
    <ul class="navigation mt-3">
    {% for menu_item in menu %}
        {% if user.is_authenticated %}
            {% if not menu_item.for_guest %}
                <li class="menu_item"><a class="menu" href="{% url menu_item.url_name %}">{{ menu_item.title }}</a></li>
            {% endif %}
        {% else %}
            {% if menu_item.for_guest %}
                <li class="menu_item"><a class="menu" href="{% url menu_item.url_name %}">{{ menu_item.title }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
     {% if user.is_authenticated %}
        <li class="menu_item"><a class="menu" href="{% url 'users:profile' user.username%}"><img style="height: 37px;" src="{% static 'users/images/account.png' %}"></a></li>
        <li class="menu_item"><a class="menu" href="{% url 'users:logout' %}">Выйти({{ user.username }})</a></li>
     {% endif %}
    </ul>
    <div class="button-sidebar-wrapper"><span class="sidebar-button"></span></div>
</nav>
<nav class="sidebar">
    <ul class="navigation-sidebar">
    {% for menu_item in menu %}
        {% if user.is_authenticated %}
            {% if menu_item.for_guest == False %}
                <li class="menu_item"><a class="menu" href="{% url menu_item.url_name %}">{{ menu_item.title }}</a></li>
            {% endif %}
        {% else %}
            {% if menu_item.for_guest %}

                <li class="menu_item"><a class="menu" href="{% url menu_item.url_name %}">{{ menu_item.title }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
    {% if user.is_authenticated %}
       <li class="menu_item"><a class="menu" href="{% url 'users:profile' user.username%}"><img style="height: 37px;" src="{% static 'users/images/account.png' %}"></a></li>
       <li class="menu_item"><a class="menu" href="{% url 'users:logout' %}">Выйти({{ user.username }})</a></li>
    {% endif %}
    </ul>
</nav>
{% endblock navigation %}
</header>
<div class="site-wrapper">
{% block content %}
{% endblock content %}
</div>
<footer>
</footer>
<script src="{% static 'main_pages/js/script.js' %}"></script>
<script type="text/javascript">
    function searchUsers()
    {
        let query = document.querySelector("#q").value;
        window.location.replace("{% url 'users:search_users' %}?q=" + query);
        return false;
    }
</script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>