images/friend/urls.py
from . import views
from django.urls import path

app_name = 'friend'

urlpatterns = [
    # Отправить заявку в друзья
    path('send_friend_request/<int:receiver_id>', views.send_friend_request, name='send_friend_request'),
    # Отменить заявку в друзья
    path('cancel_friend_request/<int:receiver_id>', views.cancel_friend_request, name='cancel_friend_request'),
    # Принять заявку в друзья
    path('accept_friend_request/<int:sender_id>', views.accept_friend_request, name='accept_friend_request'),
    # Отменить заявку в друзья
    path('reject_friend_request/<int:sender_id>', views.reject_friend_request, name='reject_friend_request'),
]

images/images/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from images import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_pages.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('friend/', include('friend.urls', namespace='friend'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('registrate/', views.RegistrateUserView.as_view(), name='registrate'),
    path('password_change/', views.UserChangePassword.as_view(), name='password_change'),
    path('password_change_done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('search_users/', views.UsersSearch.as_view(), name='search_users'),
    path('update_profile', views.UserUpdateProfile.as_view(), name='update_profile'),
    path('<slug:username>/', views.ShowUserProfile.as_view(), name='profile'),
]

images/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    """
    Расширение модели пользователя.
    Добавлено поле фотографии, показывать ли почту в профиле
    """
    photo = models.ImageField(verbose_name='Фотография', upload_to='users', blank=True, null=True)
    public_email = models.BooleanField(verbose_name='Отобразить почту', default=True)

images/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError


class LoginForm(AuthenticationForm):
    """
    Форма для ввода логина и пароля
    """
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'input'}))

    error_messages = {'invalid_login': 'Неверный логин или пароль, попробуйте заново'}


class RegisterUserForm(UserCreationForm):
    """
    Форма регистрации пользователя
    """
    username = forms.CharField(max_length=50, label='Логин', widget=forms.TextInput(attrs={'class': 'input'}))
    password1 = forms.CharField(max_length=30, label='Пароль', widget=forms.PasswordInput(attrs={'class': 'input'}))
    password2 = forms.CharField(max_length=30, label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'public_email', 'password1', 'password2']
        labels = {
            'email': 'E-mail'
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'input'})
        }

    def clean_username(self):
        """
        Метод для проверки уникальности логина
        :return:
        """
        username = self.cleaned_data['username']
        if get_user_model().objects.filter(username=username).exists():
            raise ValidationError('Данное имя занято')
        return username

    def clean_email(self):
        """
        Метод для проверки наличия аккаунта, зарегистрированного на почту
        :return:
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('На данную почту есть аккаунт')
        return email


class UserChangePasswordForm(PasswordChangeForm):
    """
    Форма для изменения пароля
    """
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label='Повторите новый пароль',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserUpdateForm(forms.ModelForm):
    """
    Форма для обновления данных пользователя
    """
    username = forms.CharField(max_length=50, label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'public_email']
        labels = {'email': 'E-mail'}
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean_username(self):
        """
        Проверка на уникальность имени пользователя
        :return:
        """
        username = self.cleaned_data['username']
        if get_user_model().objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise ValidationError('Данное имя пользователя занято')
        return username

    def clean_email(self):
        """
        Проверка на уникальность почты
        :return:
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise ValidationError('На данную почту зарегистрирован аккаунт')
        return email

images/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import LoginForm, RegisterUserForm, UserChangePasswordForm, UserUpdateForm
from django.shortcuts import get_object_or_404

from .utils import AnonymousRequiredMixin
from friend.models import FriendsList, FriendRequest

import enum


class FriendRequestStatus(enum.Enum):
    YOU_SENT_TO_THEM = -1
    NO_REQUEST_SENT = 0
    THEM_SENT_YOU = 1

# Create your views here.


class LoginUserView(AnonymousRequiredMixin, LoginView):
    """
    Класс представления для авторизации пользователя
    """
    form_class = LoginForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegistrateUserView(AnonymousRequiredMixin, CreateView):
    """
    Класс представления для регистрации пользователя
    """
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    model = get_user_model()
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('albums')

    def form_valid(self, form):
        user = form.save()
        FriendsList.objects.create(user=user)  # Создаем список друзей для данного пользователя
        return super().form_valid(form)


class ShowUserProfile(DetailView):
    """
    Класс представления для отображения профиля пользователя
    """
    template_name = 'users/account.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['profile'].username
        # Свой профиль смотрим или чужой
        context['is_self'] = True if self.request.user == context['profile'] else False
        context['cnt_albums'] = context['profile'].albums.count() if self.request.user == context['profile'] \
            else context['profile'].albums.filter(public=True).count()  # Количество альбомов
        if FriendsList.objects.filter(user=context['profile']).exists():  # Проверяем есть ли список друзей
            context['cnt_friends'] = context['profile'].friends.count()  # Получаем количество друзей
        else:
            FriendsList.objects.create(user=context['profile'])  # Создаем список друзей если его нет
            context['cnt_friends'] = 0  # Записываем количество друзей
        if not context['is_self'] and self.request.user.is_authenticated:
            context['is_auth'] = True
            if FriendsList.objects.get(user=self.request.user).friends.filter(pk=context['profile'].id):
                context['is_friend'] = True  # Если друзья, то отмечаем это
            else:
                context['is_friend'] = False  # Если не друзья
                # Если мы отправили запрос в друзья
                if FriendRequest.objects.filter(sender=self.request.user, receiver=context['profile']).exists():
                    context['request_status'] = FriendRequestStatus.YOU_SENT_TO_THEM.value
                # Если нам отправили запрос в друзья
                elif FriendRequest.objects.filter(sender=context['profile'], receiver=self.request.user).exists():
                    context['request_status'] = FriendRequestStatus.THEM_SENT_YOU.value
        else:
            context['is_auth'] = False
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(), username=self.kwargs['username'])


class UserChangePassword(LoginRequiredMixin, PasswordChangeView):
    """
    Класс представления для изменения пароля
    """
    template_name = 'users/password_change.html'
    extra_context = {'title': 'Изменить пароль'}
    form_class = UserChangePasswordForm
    success_url = reverse_lazy('users:password_change_done')


class UsersSearch(ListView):
    """
    Класс представления результатов поиска пользователей
    """
    model = get_user_model()
    context_object_name = 'profiles'  # переменная для найденных профилей
    template_name = 'users/search_profiles.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Результаты поиска по запросу {self.request.GET.get('q')}"
        return context

    def get_queryset(self):
        return get_user_model().objects.filter(username__icontains=self.request.GET.get('q'))


class UserUpdateProfile(LoginRequiredMixin, UpdateView):
    """
    Класс представления для обновления данных пользователя
    """
    form_class = UserUpdateForm
    model = get_user_model()
    template_name = 'users/update_account.html'

    def form_valid(self, form):
        self.success_url = reverse_lazy('users:profile', kwargs={'username': self.request.user.username})
        if 'photo' in form.changed_data:
            if self.get_object().photo:
                self.get_object().photo.delete()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user

images/users/templates/users/account.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="profile_wrapper">
    <div class="card profile_info bg-light shadow-lg">
        {% if profile.photo %}
        <img src="profile.photo.url" alt="Аватар" class="user_photo mb-1">
        {% else %}
        <img src="{% static 'users/images/default_profile.png' %}" alt="Аватар" class="user_photo mb-1">
        {% endif %}
        {% if profile.public_email or is_self %}
        <div class="info">
            <p class="small text-muted mb-1">Email</p>
            <p class="mb-0">{{ profile.email }}</p>
        </div>
        {% endif %}
        <div class="info">
            <p class="small text-muted mb-1">Username</p>
            <p class="mb-0">{{ profile.username }}</p>
        </div>
        {% if is_self %}
        <div class="mb-1">
            <a href="{% url 'users:update_profile' %}" class="btn btn-primary">Изменить</a>
        </div>
        <div>
            <a href="{% url 'users:password_change' %}" style="text-decoration: none;">Сменить пароль</a>
        </div>
        {% elif is_auth %}
            {% if is_friend %}
            <div class="mb-1">
                <button class="btn btn-outline-primary disabled">Вы друзья</button>
            </div>
            {% elif request_status == -1 %}
            <div class="mb-1">
                <button id="request_action" class="btn btn-outline-danger" onclick="friendRequest('{% url 'friend:cancel_friend_request' profile.id %}');" value="">Отменить заявку</button>
            </div>
            {% elif request_status == 1 %}
            <div id="actions" class="mb-1 card d-flex flex-column align-items-center" style="width: 100%;">
                    <p>Добавить в друзья</p>
                    <div class="d-flex flex-row">
                        <img id="reject" src="{% static 'users/images/close.png' %}" alt="" style="width: 38px;" class="m-1" onclick="action_friend_request('{% url 'friend:reject_friend_request' profile.id %}');">
                        <img id="accept" src="{% static 'users/images/check.png' %}" alt="" style="width: 38px;" class="m-1" onclick="action_friend_request('{% url 'friend:accept_friend_request' profile.id %}');">
                    </div>
            </div>
            {% else %}
            <div class="mb-1">
                <button id="request_action" class="btn btn-primary" onclick="friendRequest('{% url 'friend:send_friend_request' profile.id %}');">
                    Добавить в друзья</button>
            </div>
            {% endif %}
        {% endif %}
    </div>
    <div>
        <div class="card social-info mx-2 p-2">
            <div class="albums-info d-flex">
                {% if is_self %}
                    <a href="{% url 'albums' %}"><img class="logo2" src="{% static 'users/images/photo_album.png' %}"></a>
                {% else %}
                    {% if cnt_albums > 0 %}
                    <a href="{% url 'albums' %}?u={{ title }}"><img class="logo2" src="{% static 'users/images/photo_album.png' %}"></a>
                    {% else %}
                    <a href=""><img class="logo2" src="{% static 'users/images/photo_album.png' %}"></a>
                    {% endif %}
                {% endif %}

                <p class="cnt">{{ cnt_albums }}</p>
            </div>
            <p class="m-0" style="color:red;">Альбомы</p>
        </div>
        <div class="card social-info mx-2 mt-2 p-2">
            <div class="d-flex">
                <a><img class="logo2" src="{% static 'users/images/friends.png' %}"></a>
                <p class="cnt">{{ cnt_friends }}</p>
            </div>
            <p class="m-0" style="color:red;">Друзья</p>
        </div>
    </div>

</div>
<link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
<script type="text/javascript">
    let sendRequestButton = document.querySelector('#send_request');
    let cancelRequestButton = document.querySelector('#cancel_request');
    const send_url = "'{% url 'friend:send_friend_request' profile.id %}'";
    const cancel_url ="'{% url 'friend:cancel_friend_request' profile.id %}'";
    const accept_url = '{% url 'friend:accept_friend_request' profile.id %}';
    const reject_url = '{% url 'friend:reject_friend_request' profile.id %}';
    function friendRequest(url)
    {
        let request_action = document.querySelector('#request_action');  // Получаем кнопку управления
        let xhr = new XMLHttpRequest();
        xhr.open('POST', url);
        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');  // Устанавливаем заголовки
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xhr.onload = () => {
            if (xhr.status !== 200)
            {
                return;
            }
            let json = JSON.parse(xhr.responseText);
            if (json.is_success)
            {
                if (json.status == 'send')
                {
                    request_action.className = "btn btn-primary";  // Меняем класс
                    request_action.setAttribute( "onClick", "friendRequest("+send_url+");" );  // Меняем функцию при нажатии
                    request_action.innerHTML = 'Добавить в друзья';  // Меняем подпись для картинки
                }
                else
                {
                    request_action.className = "btn btn-outline-danger";  // Меняем класс
                    request_action.setAttribute( "onClick", "friendRequest("+cancel_url+");" );  // Меняем функцию при нажатии
                    request_action.innerHTML = 'Отменить заявку';  // Меняем подпись для кнопки
                }
            }
        }
        xhr.send();
    }
    function action_friend_request(url)
    {
        let actions = document.querySelector('#actions');
        let xhr = new XMLHttpRequest();
        xhr.open('POST', url);
        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');  // Устанавливаем заголовки
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xhr.onload = () =>{
            if (xhr.status !== 200){
                return;
            }
            let json = JSON.parse(xhr.responseText);
            if (json.is_success)
            {
                while (actions.firstChild)
                {
                    actions.removeChild(actions.firstChild);  // Удаляем все элементы внутри
                }
                let new_button = document.createElement('button');  // Создаем кнопку
                actions.className = 'mb-1';  // Устанавливаем новый класс для блока
                actions.setAttribute('style', '');  // Удаляем все стили
                if (json.status == 'friends')  // Если друзья
                {
                    new_button.className = 'btn btn-outline-primary disabled';
                    new_button.innerHTML = 'Вы друзья';
                }
                else  // Если отклонили запрос
                {
                    new_button.className = 'btn btn-primary';
                    new_button.innerHTML = 'Добавить в друзья';
                    new_button.setAttribute( "onClick", "friendRequest("+send_url+");" );
                }
                actions.appendChild(new_button);
            }
        }
        xhr.send();
    }
</script>
{% endblock content %}

images/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="form_wrapper">
<div class="form">
    <h2>{{ title }}</h2>
<form method="post">
    {% csrf_token %}
    <div class="errors">{{ form.non_field_errors }}</div>
    <input type="hidden" name="next" value="{{ next }}">
    {% for field in form %}
    <div class="field"><label for="{{ field.id_for_label }}" class="small form-label text-muted">{{ field.label }}</label><br>{{ field }}
        <div class="errors">{{ field.errors }}</div>
    </div>

    {% endfor %}
    <button type="submit" class="button">Войти</button>
</form>
</div>
</div>
<link href="{% static 'users/css/form.css' %}" rel="stylesheet">
{% endblock content %}

images/users/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    div.form{
        width: 360px;
        background: white;
        padding: 30px;
        box-shadow: rgba(60, 66, 87, 0.12) 0px 7px 14px 0px, rgba(0, 0, 0, 0.12) 0px 3px 6px 0px;
    }

    .errors{
        color: red;
        font-size: 14px;
    }

    .errors ul{
        list-style: none;
        padding: 0;
    }

    .errors li{
        margin-top: 5px;
    }

    .site-wrapper {
        display: flex;
        justify-content: center;
        margin-top: 30px;
}
</style>
<div class="form-wrapper">
<div class="form">
<h3>Изменить пароль</h3>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field mb-2"><label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label><br>{{ field }}
        <div class="errors">{{ field.errors }}</div>
    </div>

    {% endfor %}
    <button class="btn btn-primary" type="submit" style="width: 100%;">Изменить пароль</button>
</form>

</div>
</div>
{% endblock content %}

images/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h3>Вы успешно сменили пароль</h3>
{% endblock content %}

images/users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="form_wrapper">
    <div class="form">
        <h2>{{ title }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="errors">{{ form.non_field_errors }}</div>
         <div class="mb-2">
                <label for="{{ form.username.id_for_label }}" class="small form-label text-muted">{{ form.username.label }}</label>
                {{ form.username }}
                <div class="errors">{{ form.username.errors }}</div>
         </div>
         <div class="mb-2">
                <label for="{{ form.email.id_for_label }}" class="small form-label text-muted">{{ form.email.label }}</label>
                {{ form.email }}
                <div class="errors">{{ form.email.errors }}</div>
         </div>
        <div class="mb-2">
            {{ form.public_email }}
            <label for="{{ form.public_email.id_for_label}}" class="small form-label text-muted">{{ form.public_email.label }}</label>
            <div class="errors">{{ form.public_email.errors }}</div>
        </div>
        <div class="mb-2">
            <label for="{{ form.password1.id_for_label }}" class="small form-label text-muted">{{ form.password1.label }}</label>
            {{ form.password1 }}
            <div class="errors">{{ form.password1.errors }}</div>
        </div>
        <div class="mb-2">
            <label for="{{ form.password2.id_for_label }}" class="small form-label text-muted">{{ form.password2.label }}</label>
            {{ form.password2 }}
            <div class="errors">{{ form.password2.errors }}</div>
        </div>
        <button class="button" type="submit">Зарегистрироваться</button>
    </form>
    </div>
</div>
<link href="{% static 'users/css/form.css' %}" rel="stylesheet">
{% endblock content %}

images/users/templates/users/search_profiles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .user_photo{
      width: 58px;
    }
</style>
<div class="card bg-light m-1 p-2 d-flex flex-column align-items-center">
<h3>{{ title }}</h3>
  {% if profiles %}
  <div class="m-2 p-2 d-flex flex-wrap justify-content-center" style="width: 80%;">
    {% for profile in profiles %}
    <div class="card m-2 p-2 d-flex flex-column align-items-center" style="width: 180px;">
      {% if profile.photo %}
        <img src="profile.photo.url" alt="Аватар" class="user_photo mb-1">
        {% else %}
        <img src="{% static 'users/images/default_profile.png' %}" alt="Аватар" class="user_photo mb-1">
      {% endif %}
      <p>{{ profile.username }}</p>
      <a href="{% url 'users:profile' profile.username %}" class="btn btn-primary">Профиль</a>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <h6>Отсутствуют пользователи с таким именем</h6>
  {% endif %}
</div>
{% endblock content %}

images/users/templates/users/update_account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="profile_wrapper">
    <h3>Обновить данные</h3>
    <div class="card profile_info bg-light shadow-lg">
        {% if profile.photo %}
        <img src="profile.photo.url" alt="Аватар" class="user_photo mb-1">
        {% else %}
        <img src="{% static 'users/images/default_profile.png' %}" alt="Аватар" class="user_photo mb-1">
        {% endif %}
        <form class="d-flex flex-column" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label for="{{ field.username.id_for_label }}" class="small form-label text-muted">{{ form.username.label }}</label>
                {{ form.username }}
                <div class="errors">{{ form.username.errors }}</div>
            </div>
            <div class="mb-2">
                <label for="{{ field.email.id_for_label }}" class="small form-label text-muted">{{ form.email.label }}</label>
                {{ form.email }}
                <div class="errors">{{ form.email.errors }}</div>
            </div>
            <div class="mb-2">
                {{ form.public_email }}
                <label for="{{ field.public_email.id_for_label }}" class="form-label text-muted">{{ form.public_email.label }}</label>
            </div>

            <button class="btn btn-primary" type="submit">Сохранить</button>
        </form>
    </div>
</div>
<link rel="stylesheet" href="{% static 'users/css/update_account.css' %}">
{% endblock content %}